### ISSUE TITLE
terraformでのvercelデプロイ

### ISSUE THREAD

**Issue by Aokuma0628** [Aokuma0628/next-todo-app#12]

**Comment by Aokuma0628** [comment]
Github Actions の例

```yml

name: 'Terraform Deploy to Vercel'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    
    # 環境変数の設定
    env:
      VERCEL_API_TOKEN: ${{ secrets.VERCEL_API_TOKEN }}
      TF_VAR_vercel_api_token: ${{ secrets.VERCEL_API_TOKEN }}
      TF_VAR_database_url: ${{ secrets.DATABASE_URL }}
      TF_VAR_nextauth_secret: ${{ secrets.NEXTAUTH_SECRET }}
    
    steps:
      # リポジトリのチェックアウト
      - name: Checkout
        uses: actions/checkout@v3
      
      # Terraformのセットアップ
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
      
      # Terraformの初期化
      - name: Terraform Init
        run: |
          cd terraform
          terraform init
      
      # Terraformの計画
      - name: Terraform Plan
        id: plan
        run: |
          cd terraform
          terraform plan -no-color
        continue-on-error: true
      
      # プルリクエストの場合はコメントを追加
      - name: Update Pull Request
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Plan 📝\`${{ steps.plan.outcome }}\`
            
            <details><summary>Show Plan</summary>
            
            \`\`\`terraform
            ${process.env.PLAN}
            \`\`\`
            
            </details>`;
              
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
      
      # メインブランチへのプッシュの場合は適用
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          cd terraform
          terraform apply -auto-approve

```
